version: '3'

services:
  mongodb-autobackup-frontend:
    container_name: mongodb-autobackup-frontend
    build: .
    ports:
      - 5173:3000
    environment: 
      - PUBLIC_API_BASE_URL=http://localhost:3000
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host

networks:
  default:
    external: true
    name: mongodb-autobackup